#!/bin/bash
## CONFIG
ACTION="$@"
#[ "$ACTION" = "" ] && ACTION="status"
REPO_LIST=".gits"
USER=$(cat .github.user)
TOKEN=$(cat .github.token)
## COLORS
BLUE='\033[1;34m'
RED='\033[1;35m'
NC='\033[0m' # No Color
## START
while read -r line || [ -n "$line" ];
do
   URL=${line//[$'\t\r\n']}
   BRANCH=${URL##*/}
   FOLDER_NAME=${BRANCH//.git}
   PROJECT_BRANCH=${URL##*/github.com/}
   URL_AUTH="https://$USER:$TOKEN@github.com/$PROJECT_BRANCH"
   #FOLDER_NAME=${"sh github.projects $URL"}
   LINE="cd $FOLDER_NAME && git $ACTION && cd .."
   [ "$ACTION" = "open" ] && LINE="xdg-open $URL"
   [ "$ACTION" = "clone" ] && LINE="git clone $URL_AUTH"
   [ "$ACTION" = "" ] && LINE="echo $URL"
   PRINT=$LINE
   [ "$ACTION" = "clone" ] && LINE="git clone $URL_AUTH" && PRINT="git clone $URL"
   [ "$ACTION" != "" ] && echo "" && echo -e "${BLUE}$PRINT${NC}"
   [ "$URL" ] && eval "$LINE"
   #echo
done < $REPO_LIST