#!/bin/bash
## CONFIG
ALL="$@"
ACTION="$1"
NAME="$2"
#[ "$ACTION" = "" ] && ACTION="status"
REPO_LIST=$(cat .repos)
USER=$(cat .github.user)
TOKEN=$(cat .github.token)
TICKETS=".tickets"
## COLORS
BLUE='\033[1;34m'
RED='\033[1;35m'
NC='\033[0m' # No Color
## START
COUNTER=1

while read -r ticket || [ -n "$ticket" ];
do
    LINE="$COUNTER: $ticket"
    [ "$ACTION" = "export" ] && LINE="rm -rf $FOLDER_NAME"
    [ "$ACTION" = "import" ] && LINE="rm -rf $FOLDER_NAME"
    ## CREATE FOLDER for project with ticket number $ticket
    ## Create ticket on github for project over API
    ## prepare all repo + clone it
    [ "$ACTION" = "create" ] && LINE="rm -rf $FOLDER_NAME"
    [ "$ACTION" = "delete" ] && LINE="rm -rf $FOLDER_NAME"
    [ "$ACTION" = "update" ] && LINE="ls > $PROJECT_LIST"
    echo -e "${BLUE}$LINE${NC}"
    COUNTER=$((COUNTER+1))
done < $TICKETS
## DOCS
# https://ryanstutorials.net/bash-scripting-tutorial/bash-if-statements.php